name: dicom-router
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2
  - ca-certificates
  - certifi
  - ld_impl_linux-64
  - libffi
  - libgcc-ng
  - libgomp
  - libstdcxx-ng
  - libuuid
  - ncurses
  - openssl
  - pip
  - pydicom
  - pynetdicom
  - python=3.10 # Adjusted to python=3.10
  - pytz
  - readline
  - setuptools
  - sqlite
  - tk
  - tzdata
  - wheel
  - xz
  - zlib
  - pip:
      - dnspython==2.3.0
      - email-validator==1.3.1
      - fhir-resources==6.5.0
      - idna==3.4
      - pydantic==1.10.4
      - typing-extensions==4.4.0
      - requests==2.31.0
