name: dicom
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - greenlet=2.0.1
  - libcxx=14.0.6
  - libffi=3.4.2
  - libsqlite=3.40.0
  - libzlib=1.2.13
  - ncurses=6.3
  - openssl=3.0.11
  - pip=22.3.1
  - pydicom=2.3.1
  - pynetdicom=2.0.2
  - python=3.10.8
  - pytz=2022.7.1
  - readline=8.1.2
  - setuptools=66.0.0
  - sqlalchemy=2.0.21
  - tk=8.6.12
  - typing_extensions=4.7.1
  - tzdata=2022g
  - wheel=0.38.4
  - xz=5.2.6
  - pip:
      - blinker==1.6.3
      - cachetools==5.3.1
      - certifi==2023.7.22
      - charset-normalizer==3.3.0
      - click==8.1.7
      - cloudevents==1.10.0
      - deprecation==2.1.0
      - dnspython==2.3.0
      - email-validator==1.3.0
      - fhir-resources==6.5.0
      - flask==2.3.3
      - functions-framework==3.4.0
      - google-api-core==2.12.0
      - google-api-python-client==2.87.0
      - google-auth==2.19.1
      - google-auth-httplib2==0.1.0
      - google-cloud-pubsub==2.17.0
      - googleapis-common-protos==1.61.0
      - grpc-google-iam-v1==0.12.6
      - grpcio==1.59.0
      - grpcio-status==1.59.0
      - gunicorn==20.1.0
      - httplib2==0.22.0
      - idna==3.4
      - itsdangerous==2.1.2
      - jinja2==3.1.2
      - markupsafe==2.1.3
      - packaging==23.2
      - proto-plus==1.22.3
      - protobuf==4.24.4
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pydantic==1.10.4
      - pyparsing==3.1.1
      - requests==2.31.0
      - rsa==4.9
      - six==1.16.0
      - typing-extensions==4.4.0
      - uritemplate==4.1.1
      - urllib3==1.26.17
      - watchdog==3.0.0
      - werkzeug==3.0.0
      - firebase-admin==6.3.0
